# CONFIG for Jekyll

# Permalinks
permalink:           pretty

# Setup
title:            Recipies
description: >
  ## Hello world

  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere quos error incidunt recusandae ullam placeat dolorum, odio expedita autem praesentium! Esse reprehenderit magni quidem ab doloremque dolores, perferendis, vitae amet!
url:
baseurl:          "/cookbook"
author:
- name:           Patrick Gurr
- url:            http://smashingpat.com
- email:          smashingpat@gmail.com



# Build
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
highlighter: pygments
exclude:
- 'node_modules'
- 'bower_components'
- 'bower.json'
- 'gulpfile.js'
- 'package.json'
- 'README.md'

collections:
  recipies:
    output: true
    permalink: /recipe/:title/
    layout: "post"


defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: recipe
    values:
      layout: "post"
